# [Info] 基本信息
site_name: sudazzy # 左上角标题
site_url: https://xuxu0927.github.io/sudazzy/
site_author: Xuxu0927
site_description: 苏州大学转专业指南2.0


# [UI] 界面设置
## [top]
theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  font: 
    text: Noto Sans SC
    code: JetBrains Mono
  palette: 
    - scheme: default # 默认日间模式
      primary: blue # 上方的
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - content.code.copy # 代码复制
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer # 上一个下一个按钮
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章,文档可以直接附加到区域
  # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share # 将搜索结果分享
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github-alt
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Xuxu0927/sudazzy # 右上角点击跳转的链接
repo_name: 苏大转专业指南 # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2024 gis-xh # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/Xuxu0927
      name: GitHub | Xuxu0927 # 鼠标悬浮提示


# [Extensions] 扩展
plugins:
  - open-in-new-tab:
  - search:
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - zh
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags: # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - git-revision-date-localized: # 日期显示
      # ["date","datetime","iso_date","iso_datetime","timeago","custom"]
      type: timeago
      enable_creation_date: true # 创建时间
      timezone: Asia/Shanghai
      enable_parallel_processing: false
  - git-authors: # 显示作者
  - glightbox: # 图像缩放
  - meta-manager: # 元数据管理
  
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list: # 给图片后面添加{width="300"}设置大小
  - md_in_html: 
  - tables: 
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: false # 显示行号
      linenums_style: table
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences: # 代码块高亮插件
  - pymdownx.inlinehilite: # 段落中内置的小代码高亮
  - admonition: # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details: # admonition需要
  - pymdownx.caret: # markdown上标显示
  - pymdownx.tilde: # markdown下标显示
  - pymdownx.mark: # markdown突出显示
  - footnotes: #markdown脚注支持


extra_javascript:
  # latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - mkdocs/css/img-center.css # 图像居中
  - mkdocs/css/1.css



  # [Navigtion] 导航栏


nav:
    - 首页: index.md
    - 资格准备:
        - 资格限制: 资格准备/资格限制.md
        - 如何准备: 资格准备/如何准备.md
    - 转专业选择:
        - 转专业选择问题1: 转专业选择/转专业选择问题1.md
        - 转专业选择问题2: 转专业选择/转专业选择问题2.md
    - 转专业过程:
        - 首页: 转专业过程/index.md
        - 转专业流程:
            - 转专业流程new: 转专业过程/转专业流程/转专业流程new.md
            - 转专业流程old: 转专业过程/转专业流程/转专业流程old.md
        - 计算机科学与技术学院:
            - 概况: 转专业过程/计算机科学与技术学院/概况.md
            - 经验分享: 转专业过程/计算机科学与技术学院/经验分享/经验分享1.md
        - 电子信息学院:
            - 概况: 转专业过程/电子信息学院/概况.md
            - 经验分享: 转专业过程/电子信息学院/经验分享/经验分享1.md
        - 未来科学与工程学院:
            - 概况: 转专业过程/未来科学与工程学院/概况.md
            - 经验分享: 转专业过程/未来科学与工程学院/经验分享/经验分享.md
        - 机电工程学院:
            - 经验分享: 转专业过程/机电工程学院/经验分享/经验分享.md
            - 概况: 转专业过程/机电工程学院/概况.md
        - 轨道交通学院:
            - 经验分享: 转专业过程/轨道交通学院/经验分享/经验分享.md
            - 概况: 转专业过程/轨道交通学院/概况.md
        - 材料与化学化工学部:
            - 概况: 转专业过程/材料与化学化工学部/概况.md
            - 经验分享: 转专业过程/材料与化学化工学部/经验分享/经验分享1.md
        - 纳米科学技术学院:
            - 概况: 转专业过程/纳米科学技术学院/概况.md
            - 经验分享: 转专业过程/纳米科学技术学院/经验分享/经验分享.md
        - 光电科学与工程学院:
            - 概况: 转专业过程/光电科学与工程学院/概况.md
            - 经验分享: 转专业过程/光电科学与工程学院/经验分享/经验分享.md
        - 数学科学学院:
            - 经验分享: 转专业过程/数学科学学院/经验分享/经验分享1.md
            - 概况: 转专业过程/数学科学学院/概况.md
        - 物理科学与技术学院:
            - 概况: 转专业过程/物理科学与技术学院/概况.md
            - 经验分享: 转专业过程/物理科学与技术学院/经验分享/经验分享.md
        - 医学部:
            - 概况: 转专业过程/医学部/概况.md
            - 经验分享: 转专业过程/医学部/经验分享/经验分享.md
        - 商学院:
            - 经验分享: 转专业过程/商学院/经验分享/经验分享1.md
            - 概况: 转专业过程/商学院/概况.md
        - 文学院:
            - 概况: 转专业过程/文学院/概况.md
            - 经验分享: 转专业过程/文学院/经验分享/经验分享.md
    - 转专业之后:
        - 成功之后: 转专业之后/成功之后.md
        - 失败之后: 转专业之后/失败之后.md
        - 补修相关:
            - 举例：一个大一成功转入计科院的学生如何安排补修: 转专业之后/补修相关/举例：一个大一成功转入计科院的学生如何安排补修.md
            - 多少课程需要补修？: 转专业之后/补修相关/多少课程需要补修？.md
            - 学分自动转换: 转专业之后/补修相关/学分自动转换.md
            - 延毕问题: 转专业之后/补修相关/延毕问题.md
            - 是否落下的课程全部需要补修？: 转专业之后/补修相关/是否落下的课程全部需要补修？.md
            - 比照培养方案: 转专业之后/补修相关/比照培养方案.md
            - 补修选课: 转专业之后/补修相关/补修选课.md
            - 课程换修: 转专业之后/补修相关/课程换修.md
    - 附录:
        - 首页: 附录/index.md
        - 附录：一些可能有价值的建议: 附录/附录：一些可能有价值的建议.md
        - 杂项: 附录/杂项.md
        - 后记: 附录/后记.md
